// Fontsizes
#let tiny    = 8pt
#let smaller = 9pt
#let small   = 10pt
#let normal  = 11pt
#let large   = 14pt
#let larger  = 16pt
#let huge    = 24pt
#let huger   = 36pt

// Colors
#let code-bg         = rgb("#F5F5F5")
#let code-border     = rgb("#F5F5F5").darken(10%)
#let gray-80         = rgb("#000000").lighten(20%)
#let gray-70         = rgb("#000000").lighten(30%)
#let gray-60         = rgb("#000000").lighten(40%)
#let gray-50         = rgb("#000000").lighten(50%)
#let gray-40         = rgb("#000000").lighten(60%)
#let gray-30         = rgb("#000000").lighten(70%)
#let gray-20         = rgb("#000000").lighten(80%)
#let gray-10         = rgb("#000000").lighten(90%)
#let hei-orange      = rgb("#eb6a28").darken(20%)
#let hei-blue        = rgb("#0095d8").darken(20%)
#let hei-pink        = rgb("#da0066").darken(20%)
#let hei-yellow      = rgb("#f5c400").darken(20%)
#let hei-green       = rgb("#00925a").darken(20%)
#let spl-green       = rgb("#bed600").darken(20%)
#let spl-blue        = rgb("#00a9e0").darken(20%)
#let spl-pink        = rgb("#da0066").darken(20%)
#let color-info      = rgb("#5b75a0ff")
#let color-idea      = rgb("#ffe082ff")
#let color-warning   = rgb("#ffce31ff")
#let color-important = rgb("#f44336ff")
#let color-fire      = rgb("#fc9502ff")
#let color-rocket    = rgb("#bc5fd3ff")
#let color-todo      = rgb("#F5F5F5").darken(10%)

// Resources
#let icons-folder      = "../00-templates/icons/"
#let resources-folder  = "../04-resources/"
#let icon              = resources-folder + "icon.svg"
#let icon-check-badge  = icons-folder + "check-badge.svg"
#let icon-check-circle = icons-folder + "check-circle.svg"
#let icon-check-square = icons-folder + "check-square.svg"
#let icon-check        = icons-folder + "check.svg"
#let icon-circle       = icons-folder + "circle.svg"
#let icon-file         = icons-folder + "file.svg"
#let icon-fire         = icons-folder + "fire.svg"
#let icon-folder       = icons-folder + "folder.svg"
#let icon-idea         = icons-folder + "idea.svg"
#let icon-important    = icons-folder + "important.svg"
#let icon-info         = icons-folder + "info.svg"
#let icon-rocket       = icons-folder + "rocket.svg"
#let icon-square       = icons-folder + "square.svg"
#let icon-todo         = icons-folder + "todo.svg"
#let icon-warning      = icons-folder + "warning.svg"
#let icon-x-circle     = icons-folder + "x-circle.svg"
#let icon-x-square     = icons-folder + "x-square.svg"
#let icon-x            = icons-folder + "x.svg"
